export { default as Home } from './Home/Home';
export { default as Setting } from './Setting/Setting';
export { default as Korean } from './Korean/Korean';
export { default as Score } from './Score/Score';
export { default as Info } from './Info/Info';
export { default as Result } from './Result/Result';
export { default as Select } from './Select/Select';
export { default as Brand } from './Brand/Brand';
export { default as Speed } from './Speed/Speed';